name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: checkout cmdb-manager
      uses: actions/checkout@v3
      with:
        repository: chn-lee-yumi/cmdb-manager

    - name: enable debug interface
      uses: chn-lee-yumi/debugger-action@master

    - name: copy django statics
      run: |
        cd cmdb-manager
        pip3 install -r requirements.txt
        python3 manage.py collectstatic
        
    - name: Build Docker image
      run: |
        docker version
        # 登录阿里云镜像仓库
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-guangzhou.aliyuncs.com
        # 使用Dockerfile构建镜像
        docker build . --file Dockerfile --tag registry.cn-guangzhou.aliyuncs.com/yumi-cmdb/cmdb-frontend:beta
        # 推送镜像到镜像仓库
        docker push registry.cn-guangzhou.aliyuncs.com/yumi-cmdb/cmdb-frontend:beta
